### ISSUE TITLE
TypeError: module.watch is not a function on Meteor 1.8.2-rc.4

### ISSUE THREAD

**Issue by filipenevola** [peerlibrary/node-fiber-utils#7]
Hi @mitar, I was testing Meteor 1.8.2-rc.4 (https://github.com/meteor/meteor/pull/10522#issuecomment-546156339) in a project using `peerlibrary:reactive-publish` and I got this error below

```
TypeError: module.watch is not a function
at meteor-server.coffee (packages/peerlibrary_fiber-utils/src/meteor-server.coffee:1:1)
```

Do you think this is a Meteor issue or a package issue?

BTW, in another project that is not using `peerlibrary:reactive-publish` package this Meteor release is working fine.

**Comment by mitar** [comment]
I think you have not provided enough information here. Which version of this package have you used? Can you provide a small reproduction? I think the issue you are seeing should happen only with an old version of this package.

**Comment by mitar** [comment]
See [discussion here](https://github.com/meteor/meteor/pull/10522#issuecomment-533249023).

**Comment by filipenevola** [comment]
You are right, we were not using the more recent version. Sorry 😉
